Add project extension for setting JVM version, set default to 11
svvsaga/gradle-modules-public pull request #12
Opened 2021-11-04 12:25 UTC by geirsagberg

KB-7415

Consumers will automatically target JVM 11, but can opt out per project by setting e.g.

2021-11-04 13:16 UTC, mkotsbak requested changes

2021-11-04 13:16 UTC, mkotsbak commented
En DRY, ellers ok.

2021-11-04 14:02 UTC, geirsagberg commented on plugins/saga-build/build.gradle.kts
> +    implementation("org.jetbrains.kotlin", "kotlin-gradle-plugin", "1.5.31")
Det er ingen andre steder vi bruker kotlin-versjonen i pluginen. Vet ikke om noen måte å hente ut dette, gjør du?

2021-11-10 15:41 UTC, mkotsbak commented on plugins/saga-build/build.gradle.kts
> +    implementation("org.jetbrains.kotlin", "kotlin-gradle-plugin", "1.5.31")
Hmm, hva med å gjøre motsatt, å eksportere versjonen ut fra plugin og bruke det de andre stedene? Eller går kanskje ikke fordi man må vite versjonen i lista over plugins?

2021-11-16 08:59 UTC, geirsagberg commented on plugins/saga-build/build.gradle.kts
> +    implementation("org.jetbrains.kotlin", "kotlin-gradle-plugin", "1.5.31")
Stemmer, man må spesifisere versjonen når man velger plugin

2021-11-16 12:47 UTC, merged